### ISSUE TITLE
Not able to proceed with lando magento:setup:quick

### ISSUE THREAD

**Issue by jagiprasad-iksula** [improper/lando-magento2-template#3]
**Versions:**
 - Ubuntu 18.04]
 - Lando (fetch with: `lando version`: v3.0.0-rc.20): 
 - Docker Version (fetch with: `docker version: 17.06.1-ce`):

**Describe the bug**
I installed the docker CE and lando, everything works till the "lando magento:setup:quick", it is throwing following error :

user@N626:/var/www/html/lando-magento2-template$ lando magento
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/app/bin/magento\": stat /app/bin/magento: no such file or directory": unknown
user@N626:/var/www/html/lando-magento2-template$ lando magento:setup:quick
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/app/bin/magento\": stat /app/bin/magento: no such file or directory": unknown
user@N626:/var/www/html/lando-magento2-template$ 

Now not able to proceed with https://magento2.lndo.site , it is throwing 

404 Not Found
nginx/1.14.2

**To Reproduce**

**Expected behavior**
The command was for quick magento set up, which should quickly set up the magento for the given  URL, so that I can visit the default magento version and could explore more 

**Screenshots**
PFA

Can anybody tell me what and where things are going wrong.

**Comment by tylers-username** [comment]
Lando was undergoing pretty rapid development when this was put together. There's a chance a breaking change was introduced by Lando.

I'll look into this ASAP and let you know what I find.

**Comment by jagiprasad-iksula** [comment]
**I tried another way for magento set up, I directly copied the default magento codebase into one directory.
Then did ****lando init****  below the command executed:**
=====================================================================
user@N626:/var/www/html/magento2.3.2$ lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use? lamp
? Where is your webroot relative to the init destination? .
? What do you want to call this app? magento2.3.2

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run `lando start` to get rolling.
Check the LOCATION printed below if you are unsure where to go.

Oh... and here are some vitals:

 NAME      magento2.3.2                                     
 LOCATION  /var/www/html/magento2.3.2                       
 RECIPE    lamp                                             
 DOCS      https://docs.devwithlando.io/tutorials/lamp.html 

user@N626:/var/www/html/magento2.3.2$ lando start
Let's get this party started! Starting app..
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
.
.
.
.
.
.
Waiting until database service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            magento2.3.2                       
 LOCATION        /var/www/html/magento2.3.2         
 SERVICES        appserver, database                
 APPSERVER URLS  https://localhost:32780            
                 http://localhost:32781             
                 http://magento2.3.2.lndo.site:8080 
                 https://magento2.3.2.lndo.site   
====================================================================

I came to one magento URL, when open this link it start the default magento set up but here new issue came up see the details below :
PHP Version Check
Your PHP version is 7.3.9. The required PHP version is ~7.1.3||~7.2.0. Hide detail

Download and install PHP from www.php.net using this PHP Documentation.

For additional assistance, contact your hosting provider.
PHP Settings Check *

Your PHP settings are correct.

Need Help?
PHP Extension Help
PHP Extensions Check

1 missing PHP extensions.

The best way to resolve this is to install the correct missing extensions. The exact fix depends on our server, your host, and other system variables.
Our PHP extension help can get you started.

For additional assistance, contact your hosting provider.

    PHP Extension xsl.  is missing extension..

=====================================================================

How can we upgrade and downgrade the PHP version: as I have used below versions:

Versions:

    Ubuntu 18.04]
    Lando (fetch with: lando version: v3.0.0-rc.20):
    Docker Version (fetch with: docker version: 17.06.1-ce):

**Awaiting your reply!!!**

**Comment by ivanovf** [comment]
I have the same issue with ubuntu 16.04, and a tried to install it using lamp as recipe but the xsl extension error came up. Is there a diferent way to install it using lando?

**Comment by KjoeKjoe** [comment]
@jagiprasad-iksula @ivanovf To fix xls extension you can rebuild the box 'lando rebuild' this will install the xls extension.

**Comment by KjoeKjoe** [comment]
> @jagiprasad-iksula @ivanovf To fix xls extension you can rebuild the box 'lando rebuild' this will install the xls extension.
 
I took the following steps to make Magento 2 work at current version:

```
git clone https://github.com/improper/lando-magento2-template.git magento2
cd magento2/
lando magento:download
lando rebuild
lando start && lando composer install && lando magento:setup:quick #Optional --use-sample-data

lando magento sampledata:deploy && lando magento setup:upgrade && lando magento setup:di:compile && lando magento setup:static-content:deploy -f && lando magento deploy:mode:set developer
```

The last command with deploy and stuff is set in the lando.base.yml of my project so i wont have to do that again.

give it a spin :)

Note: is you get an error of invalid XML "is_syncronised" which COULD happen sometimes you have to go to:

vendor/module-inventory-catalog/etc/communication.xml

remove all 'is_synchronized=false' only those!

**Comment by tylers-username** [comment]
@jagiprasad-iksula - based on the original issue, it seems like composer may have failed installation. I am using the same OS and version that you are (Ubuntu 18) and followed the provided documentation without issue.

In https://github.com/improper/lando-magento2-template/issues/3#issuecomment-532072372 you mentioned that you went with the `lando init` option. If you're going to do that, please use my config as a comparison. My `.lando.base.yml` has a build hook that installs the required extensions. You'll also run into issues if you do not copy my NGINX config because Lando will not know how to route all of the required Magento requests.

@ivanovf - this is relevant to what you mentioned as well. Except if you are going to use `lando init` and you want to copy my setup then you will need to use `lemp` instead.

@KjoeKjoe - sounds like the setup worked for you, glad to hear it. I just added a `.lando.local.sample.yml` as well as a `.lando.yml` to the project to help projects get off the ground more quickly.

- `.lando.local.yml` - a git ignored file that your dev team will use locally to override `.lando.base.yml` and `.lando.yml`
- `.lando.yml` - this is your project-specific config. Add services, tooling and build hooks!
- `.lando.base.yml` - this is just to define what Magento needs to get off the ground. Your project and your devs should not ever need to modify this. Consider this the "base template"

**Comment by tylers-username** [comment]
Closing. Will re-open as needed.
