### ISSUE TITLE
New Pull Requests

### ISSUE THREAD

**Issue by azmeehan** [improper/lando-magento2-template#5]
Hey Man,

Been using this a little bit lately, finding it pretty useful so thanks for putting it together!

Are you taking pull requests I have a couple of suggestions that might save some headaches for new users.

**Comment by tylers-username** [comment]
I'm happy to hear that it has been useful.

Don't hesitate to open a PR. Anything included there or additional feedback you might have may be useful in helping the Lando team determine how best to implement the Magento recipe that's being considered.

**Comment by azmeehan** [comment]
Hi Tyler,

Any thoughts on the changes in the pull request Ive added?

Also Ive tested with the latest lando release v3.0.0-rrc.4 and it seems to work ok as well.

Cheers,

Aaron
